stack = []
stack.uppend("A") # [A]
stack.uppend("B") # [A, B]
stack.pop()       # [A]
stack.uppend("C") # [A, C]
stack.uppend("D") # [A, C, D]
stack.pop()       # [A, C]
stack.uppend("E") # [A, C, E]
stack.uppend("F") # [A, C, E, F]
stack.uppend("G") # [A, C, E, F, G]
stack.uppend("H") # [A, C, E, F, G, H]
stack.pop()       # [A, C, E, F, G]
stack.pop()       # [A, C, E, F]
stack.uppend("I") # [A, C, E, F, I]
stack.pop()       # [A, C, E, F]
stack.pop()       # [A, C, E]
stack.pop()       # [A, C]
stack.uppend("J") # [A, C, J]
stack.uppend("K") # [A, C, J, K]
stack.uppend("L") # [A, C, J, K, L]
stack.uppend("M") # [A, C, J, K, L, M]
stack.pop()       # [A, C, J, K, L]
stack.uppend("N") # [A, C, J, K, L, N]
stack.uppend("O") # [A, C, J, K, L, N, O]
stack.uppend("P") # [A, C, J, K, L, N, O, P]
stack.pop()       # [A, C, J, K, L, N, O]
stack.pop()       # [A, C, J, K, L, N]
stack.pop()       # [A, C, J, K, L]
stack.pop()       # [A, C, J, K]
stack.uppend("Q") # [A, C, J, K, Q]
stack.uppend("R") # [A, C, J, K, Q, R]
stack.uppend("S") # [A, C, J, K, Q, R, S]
stack.uppend("T") # [A, C, J, K, Q, R, S, T]
stack.pop()       # [A, C, J, K, Q, R, S]
stack.uppend("U") # [A, C, J, K, Q, R, S, U]
stack.uppend("V") # [A, C, J, K, Q, R, S, U, V]
stack.pop()       # [A, C, J, K, Q, R, S, U,]
stack.uppend("W") # [A, C, J, K, Q, R, S, U, W]
stack.uppend("X") # [A, C, J, K, Q, R, S, U, W, X]
stack.pop()       # [A, C, J, K, Q, R, S, U, W]
stack.uppend("Y") # [A, C, J, K, Q, R, S, U, W, Y]
stack.uppend("Z") # [A, C, J, K, Q, R, S, U, W, Y, Z]
print(stack)
