stack = []
stack.append("A") # [A]
stack.append("B") # [A, B]
stack.pop()       # [A]
stack.append("C") # [A, C]
stack.append("D") # [A, C, D]
stack.pop()       # [A, C]
stack.append("E") # [A, C, E]
stack.append("F") # [A, C, E, F]
stack.append("G") # [A, C, E, F, G]
stack.append("H") # [A, C, E, F, G, H]
stack.pop()       # [A, C, E, F, G]
stack.pop()       # [A, C, E, F]
stack.append("I") # [A, C, E, F, I]
stack.pop()       # [A, C, E, F]
stack.pop()       # [A, C, E]
stack.pop()       # [A, C]
stack.append("J") # [A, C, J]
stack.append("K") # [A, C, J, K]
stack.append("L") # [A, C, J, K, L]
stack.append("M") # [A, C, J, K, L, M]
stack.pop()       # [A, C, J, K, L]
stack.append("N") # [A, C, J, K, L, N]
stack.append("O") # [A, C, J, K, L, N, O]
stack.append("P") # [A, C, J, K, L, N, O, P]
stack.pop()       # [A, C, J, K, L, N, O]
stack.pop()       # [A, C, J, K, L, N]
stack.pop()       # [A, C, J, K, L]
stack.pop()       # [A, C, J, K]
stack.append("Q") # [A, C, J, K, Q]
stack.append("R") # [A, C, J, K, Q, R]
stack.append("S") # [A, C, J, K, Q, R, S]
stack.append("T") # [A, C, J, K, Q, R, S, T]
stack.pop()       # [A, C, J, K, Q, R, S]
stack.append("U") # [A, C, J, K, Q, R, S, U]
stack.append("V") # [A, C, J, K, Q, R, S, U, V]
stack.pop()       # [A, C, J, K, Q, R, S, U,]
stack.append("W") # [A, C, J, K, Q, R, S, U, W]
stack.append("X") # [A, C, J, K, Q, R, S, U, W, X]
stack.pop()       # [A, C, J, K, Q, R, S, U, W]
stack.append("Y") # [A, C, J, K, Q, R, S, U, W, Y]
stack.append("Z") # [A, C, J, K, Q, R, S, U, W, Y, Z]
print(stack)
